### ISSUE TITLE
Overlay in external windows 

### ISSUE THREAD

**Issue by gamersalpha** [brightcove/videojs-overlay#58]
Hello, 

i now is crazt, but it' will be very cool for me :)

can we have the overlay on multi windows ? 

iwant see the video on evry tab i m go on the navigateur ?

and the best of the best, i want the video over all my windows apps ?

what do u think please ?

**Comment by gkatsev** [comment]
It's definitely possible to make a new window and putting the player into it. Though, without making it a browser extension you won't be able to force it to stay in front of the tabs when switching tabs and windows.
Also, this plugin is intended for creating text or image (or other) overlays on top of the player in the page rather than turning the player into an overlay.

Hope that helps.
